### ISSUE TITLE
Some way to provision this with Swarm?

### ISSUE THREAD

**Issue by byrnedo** [jpetazzo/dind#102]
Is there some way to make a swarm out of dind containers? I guess I just need an ssh server running in the container..

**Comment by jpetazzo** [comment]
Sorry, I wasn't monitoring issues on this repo; yes it is possible, and you don't need an SSH server :-)

**Comment by tianon** [comment]
https://github.com/tianon/docker-dind-cluster might be of some interest :innocent:

**Comment by jpetazzo** [comment]
Solid :)

On Wed, Jul 13, 2016 at 4:22 PM, Tianon Gravi <notifications@github.com>
wrote:

> https://github.com/tianon/docker-dind-cluster might be of some interest 😇
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jpetazzo/dind/issues/102#issuecomment-232515232>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAKd2b7q-6aauBUBZWaW2t_Ev_xIPHz2ks5qVXM-gaJpZM4HKWWo>
> .
>



-- 
@jpetazzo <https://twitter.com/jpetazzo>
http://jpetazzo.github.io/
<http://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/>
