### ISSUE TITLE
ERRO[6246] containerd: notify OOM events 

### ISSUE THREAD

**Issue by AJNOURI** [jpetazzo/dind#107]
**Environement:**
root@dind2:/# docker -v
Docker version 1.11.2, build b9f10c9

**Docker host**
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.5 (jessie)
Release:	8.5
Codename:	jessie

Linux gns3-iouvm 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

--------------

Using "--privileged" as instructed:

`docker run --privileged -t -i dind`

When I start a container inside dind, I have the following message:

> fd227438d2a0d6689fcf80b4302f8b05ecd2199ad82f946b41680090d8597547
> ERRO[6246] containerd: notify OOM events                 error=open memory.oom_control: no such file or directory

Doesn't seem to have incidence, container is running and reachable from outside

Looks like priorly solved with previous version https://github.com/docker/containerd/issues/188 but stll experiencing this with 1.11.2, build b9f10c9

**Comment by jpetazzo** [comment]
I think this can safely be ignored :-) But thanks for reporting!
