### ISSUE TITLE
How can I config DOCKER_OPTS when run container ?

### ISSUE THREAD

**Issue by ivkean** [jpetazzo/dind#111]
Hi @jpetazzo ,

How can i pass something like DOCKER_OPTS="--insecure-registry domain.com" when run command `docker run ...` 

Thanks :).

**Comment by jpetazzo** [comment]
I'd suggest to look at the [images tagged `:dind` in the official `docker` images on the Docker Hub](https://hub.docker.com/_/docker/) instead – this repository is not maintained anymore :-)
