### ISSUE TITLE
ran into some issues running the docker run command

### ISSUE THREAD

**Issue by tomvisions** [jpetazzo/dind#113]
I cloned the folder
 git clone https://github.com/jpetazzo/dind.git

ran this...
tcruickshank@tom-build:~/test/dind$ docker build -t dind .

then....

tcruickshank@tom-build:~/test/dind$ docker run --privileged -t -i dind
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
INFO[0000] libcontainerd: new containerd process, pid: 69
INFO[0001] Graph migration to content-addressability took 0.00 seconds
WARN[0001] Your kernel does not support swap memory limit.
WARN[0001] Your kernel does not support cgroup rt period
WARN[0001] Your kernel does not support cgroup rt runtime
INFO[0001] Loading containers: start.
WARN[0001] Running modprobe bridge br_netfilter failed with message: modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'
, error: exit status 1
WARN[0001] Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'`, error: exit status 1
WARN[0001] Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-57-generic/modules.dep.bin'`, error: exit status 1
INFO[0001] Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[0001] Loading containers: done.
INFO[0001] Daemon has completed initialization
INFO[0001] Docker daemon                                 commit=49bf474 graphdriver=aufs version=1.13.0
INFO[0001] API listen on /var/run/docker.sock

**Comment by jpetazzo** [comment]
Hi,

I would suggest that you try the official, upstream `dind` images. Check for the [images tagged `:dind` in the official `docker` images on the Docker Hub](https://hub.docker.com/_/docker/)!
