### ISSUE TITLE
Cannot restart docker service inside the container

### ISSUE THREAD

**Issue by andrejmaya** [jpetazzo/dind#115]
Dear @jpetazzo,

I want to add insecure-registry flag to DOCKER_OPTS under /etc/default/docker and restart the docker service. 

When I do `service docker restart` its giving me:

`mount: cgroup already mounted or cpu busy
mount: according to mtab, cgroup is already mounted on /sys/fs/cgroup/cpu,cpuacct
rmdir: failed to remove 'cpu': Not a directory
mount: cgroup already mounted or cpuacct busy
mount: according to mtab, cgroup is already mounted on /sys/fs/cgroup/cpu,cpuacct
rmdir: failed to remove 'cpuacct': Not a directory
mount: cgroup already mounted or net_cls busy
mount: according to mtab, cgroup is already mounted on /sys/fs/cgroup/net_cls,net_prio
rmdir: failed to remove 'net_cls': Not a directory
mount: cgroup already mounted or net_prio busy
mount: according to mtab, cgroup is already mounted on /sys/fs/cgroup/net_cls,net_prio
rmdir: failed to remove 'net_prio': Not a directory
` 
back. 

When I do `service docker status` it says: `Docker is not running`. However I can run `docker ps` e.g.

Could you please help?

regards

**Comment by jpetazzo** [comment]
The `service ...` command works with an init system like upstart or systemd. In DinD, the Docker Engine is started directly. To change the Docker Engine flags, you could change the CMD of your image instead.
