### ISSUE TITLE
dind, swarm cluster, and container communication

### ISSUE THREAD

**Issue by jamiejackson** [jpetazzo/dind#116]
I've been asking this on #docker on Freenode, and the [Docker Forums](https://forums.docker.com/t/docker-swarm-docker-in-docker-container-communication/34425), but I think the Inception aspect is scaring people off; therefore, I'm trying here.

----

I'm playing with Docker Swarm by using a swarm of dind containers.

However, I can't access one container from another. For instance, I need to be able to reach `master` from `slave`. I seem to be able to ping it, but I can't access it over `3306` or `3307`.

Here's my configuration, including the swarm bootstrapping, the docker compose configuration, and the way I'm starting the stack:

https://gist.github.com/jamiejackson/df318fb656115f2e72f819f7f50c9d1a#file-bootstrap_swarm-sh-L41-L50

```
$ service_name=db_slave
$ worker_node=$(docker service ps db --filter "name=db_slave."  --format "{{.Node}}")
$ docker exec -it ${worker_node} \
>   /bin/sh -c '
>     docker exec -it $(docker ps --filter "name=db_slave.*" --format "{{.ID}}") \
>       nc -vz -w 1 master 3307
>   '
Warning: inverse host lookup failed for 10.0.0.2: Unknown host
master [10.0.0.2] 3307 (?) : Connection timed out
$ docker exec -it ${worker_node}   /bin/sh -c '
    docker exec -it $(docker ps --filter "name=db_slave.*" --format "{{.ID}}") \
      nc -vz -w 1 master 3306
  '
Warning: inverse host lookup failed for 10.0.0.2: Unknown host
master [10.0.0.2] 3306 (mysql) : Connection timed out
```

I highlighted the kitchen sink port publishing--it was an(other failed) attempt at getting communication working.

I'm probably doing multiple things wrong here.

Help?

**Comment by jpetazzo** [comment]
I replied on the Docker forums. I'll close this issue here to avoid duplication!
