### ISSUE TITLE
Connecting another running container to Docker in Docker socket

### ISSUE THREAD

**Issue by mylespollie** [jpetazzo/dind#118]
I'm trying to implement an image registry scanner.  I've found that the scanner I'm using needs access to a docker socket, but I don't want to connect it to the cluster's docker socket as it appears to be very unsafe.  I'd like to run Docker in Docker so I can pull the images from the registry to dind and then connect the scanner container dind's socket to scan the images.  Is this possible?

**Comment by jpetazzo** [comment]
Yes; but if you are concerned about safety, DinD is not the right answer (it requires containers with elevated privileges). The safest solution would be to have a Docker Engine on the side, dedicated to the use of your security scanner; and add an [authorization plugin](https://docs.docker.com/engine/extend/plugins_authorization/) to limit the API commands that it can execute (and disable privileged containers, for instance).
