### ISSUE TITLE
Support: How to install apt-get inside Dockerfile

### ISSUE THREAD

**Issue by ORESoftware** [jpetazzo/dind#119]
I have the following Dockerfile contents:

```dockerfile
FROM docker:dind
RUN apt-get update && \
      apt-get -y install sudo
```

I get this error:
`/bin/sh: apt-get: not found`

it's not clear to me if docker:dind uses Debian or what not. What I need to do is install nodejs and a few other things in the Dockerfile/image.

**Comment by jpetazzo** [comment]
The current version of `docker:dind` is based off the Alpine distribution. If you want to install packages, you should use the `apk` package manager.
