### ISSUE TITLE
Fedora image not working

### ISSUE THREAD

**Issue by tlf30** [jpetazzo/dind#122]
Hello,
I am trying to get the fedora image working, but have not had any luck. I am getting the message:
```
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
/usr/local/bin/wrapdocker: line 100: dockerd: command not found
Timed out trying to connect to internal docker host.
```

Any help would be great!
Thank you,
Trevor Flynn

**Comment by jpetazzo** [comment]
Hi Trevor,

I'm sorry, I never used the fedora image, so I have no idea why it would output that :-(
