### ISSUE TITLE
docker: Error response from daemon

### ISSUE THREAD

**Issue by fatg1988** [jpetazzo/dind#123]
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file

Kernel Version: 3.10.0-229.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64

docker run --privileged -t -i jpetazzo/dind
docker: Error response from daemon: mkdir /data/docker/overlay/fed05111111d5a5b10bc50a64c861a17531f234acc504e787addbe6caf72f1e7-init/merged/dev/shm: invalid argument.
See 'docker run --help'.

**Comment by jpetazzo** [comment]
Hi,

Docker Engine 1.13.1 is very, very old and unsupported. I would recommend to try with the latest CE (stable or edge) version.

Thanks,
