### ISSUE TITLE
Docker in Docker: Not in privileged mode.

### ISSUE THREAD

**Issue by shivamgupta01** [jpetazzo/dind#129]
Hey, how can I run Docker in Docker without privileged mode. 

The main objective is to run the docker login, pull and push command. Also I want to run this on AWS fargate which does not allows us to run in privileged mode. 

Any opinions what can be done for this?

Thanks in Advance.

**Comment by thaJeztah** [comment]
Do you need to run a daemon, or just need the client commands to connect to an existing daemon?

If you only need the client, you don't need privileged, and can use the official docker images from Docker Hub, and bind-mount the docker socket, for example:

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:18.03 sh
/ # docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.2
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.06.0-ce-rc3
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   cbfa3d9
  Built:        Thu Jul 12 05:26:13 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by tianon** [comment]
You might also be interested in the "distribution" pieces of containerd which decouple the image distribution/storage from the runtime bits (so you'd be able to actually pull/push from within an unprivileged container, even without a daemon).

**Comment by shivamgupta01** [comment]
Docker:latest images just comes up with the docker installed in it. The architecture requires to run the containers like AWS Lambda functions, thats why I am trying to use AWS Fargate. If we mount the docker.sock file, the containers will be able to access the host machines Containers which Fargate or any other cloud provider will not allow unless you are not using your own EC2  instance. 

The best way was to use your wrapdocker script in the background and let the docker push pull command do it magic.

**Comment by shivamgupta01** [comment]
For your earlier commend, where can I get more information about it?

**Comment by thaJeztah** [comment]
Note that the `dind` script in this repository is quite outdated; most of it is no longer needed (the current `dind` script in the moby repository is really short now, and mainly for some edge conditions; https://github.com/moby/moby/blob/master/hack/dind

but @tianon may be able to tell more in detail.

**Comment by tianon** [comment]
That's true -- you can run Docker-in-Docker with a pretty stock `--privileged` container these days.

However, if what you're looking to do is push/pull images, Docker currently only does so via the graph drivers, which are going to require mounting (and thus increased privileges).  You _might_ be able to do something crazy with the `vfs` driver, but it will _not_ be performant (and will be quite a resource hog).

**Comment by shivamgupta01** [comment]
Thank you so much guys for helping me out. I will try out these options. 

Closing this issue.

**Comment by ghost** [comment]
@shivamgupta01 Did you have any luck?
