### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by alessandro-candon** [jpetazzo/dind#130]
Hello,
I'm trying to use this image to run a docker-compose inside the container in order to build more images at the same time in the same jks server.

When I try to run the container with this command as reported in the doc 
`docker run -it --privileged docker:dind sh `

and then run 
`docker ps`

I receive this error 

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

![screenshot 2018-10-24 at 16 25 04](https://user-images.githubusercontent.com/44228481/47437817-98ee5080-d7a9-11e8-84df-462dc139ec1b.png)

Do you know any solution or workaround?

**Comment by dangminhtruong** [comment]
Same problem. Run in detach mode ( -d ) it work perfect. But `docker run --name dockerdin --privileged -it docker:dind sh` it does't work anymore... Too weird.

**Comment by dangminhtruong** [comment]
Same problem. Run in detach mode ( -d ) it work perfect. But docker run --name dockerdin --privileged -it docker:dind sh it does't work anymore... I guess this happen because this docker image entrypoint need time to settup and start docker inside container...

**Comment by alessandro-candon** [comment]
Thank you, 
I find a workaround, using inside the container `docerd & ` to run demon...

I hope it helps

**Comment by dangminhtruong** [comment]
@alessandro-candon Could you explain more about your solution for me ? I met this problem few hours ago, you edited entrypoint file or something ?

**Comment by dangminhtruong** [comment]
@alessandro-candon It works ! Thank you ^^

**Comment by alessandro-candon** [comment]
Perfect..!
But it is so bad soultion...

**Comment by amir-bengherbi** [comment]
@alessandro-candon thank you! this saved me after 6h of struggling 
ps: there is a typo in the command : `dockerd &`
