### ISSUE TITLE
wrapdocker is missing in docker:dind

### ISSUE THREAD

**Issue by mydockergit** [jpetazzo/dind#133]
I ran `docker run --rm --privileged -ti docker:dind wrapdocker` and received:  
`/usr/local/bin/dockerd-entrypoint.sh: exec: line 23: wrapdocker: not found`

If I build the image from `DockerFile` and then run the container, I have the wrapdocker.
It seems to be missing in the `docker:dind` from docker hub.

**Comment by jpetazzo** [comment]
Hi!

I'm not maintaining the `docker:dind` image, unfortunately, so I cannot help with that, I'm sorry :(
