### ISSUE TITLE
docker-compose in DinD

### ISSUE THREAD

**Issue by denisb411** [jpetazzo/dind#134]
After running DinD image I noticed that docker-compose is not installed.

I tried to install with:

```
curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
But this seems not to work.

How can I get docker-compose running?

**Comment by jpetazzo** [comment]
Hi,

This repository is not maintained anymore; it's here only for historical reasons.

But you can check the `docker:dind` images, that replace it and (I think) provide similar features!
