### ISSUE TITLE
[error] mount point /sys/fs/cgroup does not exist

### ISSUE THREAD

**Issue by lcheng61** [jpetazzo/dind#17]
Hi,

I like the idea of dind and would like to try it out. Can someone help me on the following errors ?

[root@localhost ~]# docker run -privileged jpetazzo/dind
Warning: '-privileged' is deprecated, it will be replaced by '--privileged' soon. See usage.
mkdir: cannot create directory '/sys/fs/cgroup': No such file or directory
mount: mount point /sys/fs/cgroup does not exist
Could not make a tmpfs mount. Did you use -privileged?

[root@localhost ~]# docker --version
Docker version 0.11.1, build fb99f99/0.11.1

**Comment by kyleschlosser** [comment]
Is there any updated advice on this issue? I am on Redhat 6.6 with Kernel 2.6.32-504.8.1.el6.x86_64 and Docker 1.5.0 and I am looking for a workaround.

**Comment by jpetazzo** [comment]
@kyleschlosser, which exact message are you getting?

This one:

```
mkdir: cannot create directory '/sys/fs/cgroup': No such file or directory
mount: mount point /sys/fs/cgroup does not exist
Could not make a tmpfs mount. Did you use -privileged?
```

or something else?

**Comment by kyleschlosser** [comment]
Yes, that is the error I am getting: 

    $ docker run --privileged -t -i dind
    mkdir: cannot create directory '/sys/fs/cgroup': No such file or directory
    mount: mount point /sys/fs/cgroup does not exist
    Could not make a tmpfs mount. Did you use --privileged?

**Comment by glaudiston** [comment]
I'm with this issue too.

There is no /sys/fs/cgroup ... 
    $ ls /sys/fs
    ext4

Some system info:

    $ uname -a
    Linux kimo.cit 2.6.32-504.12.2.el6.x86_64 #1 SMP Sun Feb 1 12:14:02 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

    $ cat /etc/redhat-release 
    Red Hat Enterprise Linux Server release 6.6 (Santiago)

    $ cat /etc/lsb-release
    LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch


    $ cat /proc/cgroups 
    #subsys_name    hierarchy       num_cgroups     enabled
    cpuset  1       1       1
    ns      0       1       1
    cpu     2       1       1
    cpuacct 3       1       1
    memory  0       1       1
    devices 4       1       1
    freezer 5       1       1
    net_cls 6       1       1
    blkio   7       1       1
    perf_event      0       1       1
    net_prio        0       1       1

**Comment by jpetazzo** [comment]
This *might* be because you're using 2.6.32 kernel, and/or some SELinux restriction.

Can you:
- test manually if you can `mkdir /sys/fs/cgroup` manually in the container?
- test with a more recent kernel?

Thank you!

**Comment by cancan101** [comment]
I am getting:
```
root@24c8e810e17e:/# mkdir -p /sys/fs/cgroup
mkdir: cannot create directory '/sys/fs/cgroup': No such file or directory
```

**Comment by jpetazzo** [comment]
This is very confusing. Maybe SELinux? Check kernel logs, try with a more permissive profile? Sorry, I wish I could be more useful there, but I kind of threw the towel with 2.6 kernels... Really sorry :/

**Comment by yakhyadabo** [comment]
I'm experiencing the same issue. Here's the output message of the daemon : 

[mkdir: cannot create directory '/sys/fs/cgroup': No such file or directory
mount: mount point /sys/fs/cgroup does not exist
Could not make a tmpfs mount. Did you use -privileged?"]

OS : Centos 6.6
Kernel : 2.6 

Docker version : 
Client version: 1.5.0
Client API version: 1.17

**Comment by jpetazzo** [comment]
There is now an official [docker:dind](https://hub.docker.com/_/docker/) image upstream! I invite you to test it, since it is actively maintained. Thank you!
