### ISSUE TITLE
Disk space usage

### ISSUE THREAD

**Issue by Furze** [jpetazzo/dind#27]
Removing images and containers within dind doesn't allow the host operating system to reclaim disk space. 

Linking issue docker/docker#7285 from docker/docker as it is related to jpetazzo/dind

**Comment by iffy** [comment]
So is there no way to reclaim the space as described here? https://github.com/jpetazzo/dind#important-warning-about-disk-usage

**Comment by jpetazzo** [comment]
Well, it's not really a dind issue, but a Docker issue. More specifically, a volume management issue.

I will close this issue, unless someone has a good reason to think that this is *specifically* a dind issue.

Thank you!
