### ISSUE TITLE
Update Docker to latest

### ISSUE THREAD

**Issue by dristic** [jpetazzo/dind#29]
I was having some issues running docker, specifically with the new `--privileged` flag. I had to update docker on the machine and these steps did the trick: http://askubuntu.com/questions/472412/how-do-i-upgrade-docker to get a more recent version.

I am not sure if this is the correct way to update so I will leave it up to you, but wanted to point it out.

**Comment by kojiromike** [comment]
Is this relevant to dind, or the default docker in Ubuntu? I'm confused. If I run dind I do get the latest docker:

```
# docker version
Client version: 1.6.1
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 97cd073
OS/Arch (client): linux/amd64
Server version: 1.6.1
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 97cd073
OS/Arch (server): linux/amd64
```

**Comment by dristic** [comment]
It's been a while since I've looked at it. Previously it was an issue with the version of dind that didn't allow using the `--privileged` flag. This might have been updated since then though.

**Comment by jpetazzo** [comment]
Thanks for reporting this. I hope it can help others!
