### ISSUE TITLE
Allow calling of other command

### ISSUE THREAD

**Issue by breerly** [jpetazzo/dind#31]
Ideally when you extend from the dind you'd like to execute your own command. 

I've tried something like the following with no luck:

```
docker run -i -t --privileged jpetazzo/dind "wrapdocker && mycommandhere"
```

Ideas?

**Comment by jpetazzo** [comment]
I *think* that #42 (that I just merged) might help. What do you think?>

**Comment by jpetazzo** [comment]
Closing old issues.
