### ISSUE TITLE
Versioning of dind (wrapdocker)?

### ISSUE THREAD

**Issue by leeola** [jpetazzo/dind#32]
Would it be possibly to start versioning this project _(with git tags, and etc)_?

The purpose being that i am not using the Dockerfile of this project directly. I am however, using wrapdocker. In typical dependency fashion, it would be really nice if i were able to ensure stability of wrapdocker by referring to a single version. As well as know that future versions do/do-not have an API change (semver).

As another point, i'd like to introduce a couple small changes to wrapdocker that would change the API (i'm not confident that they would be merged haha), but again, without versioning that feels super wrong to do to people.

So, thoughts? Perhaps this repo is not the best place to version something like wrapdocker, and if so, any thoughts on what might be better?

**Comment by jpetazzo** [comment]
Hi!

I agree that this would be nice.

How would you recommend to implement this?

**Comment by jpetazzo** [comment]
If other people need this: check the [images tagged `:dind` in the official `docker` images on the Docker Hub](https://hub.docker.com/_/docker/)!
