### ISSUE TITLE
saving docker images inside dind

### ISSUE THREAD

**Issue by uptownhr** [jpetazzo/dind#34]
anyway to make it possible to save or preload the dind with other docker images and containers?

When I attempt to commit a dind container with preloaded docker images and containers, the commit goes through but new containers off of the commit will have lost all of it's docker related images/containers.

I assume this is related to having to mount /var/lib/docker but is there any way around this?

**Comment by Freyskeyd** [comment]
@cedvan i'm trying to do it too

**Comment by Freyskeyd** [comment]
You can do it with:
```
docker run --privileged \
> -v /var/lib/docker/repositories-aufs:/var/lib/docker/repositories-aufs \
> -v /var/lib/docker/graph:/var/lib/docker/graph \
> -v /var/lib/docker/aufs:/var/lib/docker/aufs \
> -ti jpetazzo/dind
```

**Comment by cedvan** [comment]
Thank you :)

**Comment by Freyskeyd** [comment]
I just have one issue when pull image inside a container.
On the host, the image is missing.
On a freshly created container the image is accessible...

**Comment by jpetazzo** [comment]
*Don't* share `/var/lib/docker`, it is not intended to be shared between multiple demons!

When one demon pulls an image, the other demon will not be aware of it and you will have problems.

You *can* do it if you don't pull images (or if you pull images only from one demon and don't intend to have those images visible in the other demons).

**Comment by ureyes84** [comment]
Thanks! We actually found out about this the hard way.

However... you gave us an invaluable tip in PyCon Montreal to get docker from within a container by mounting: `/var/run/docker.sock`

**Comment by jpetazzo** [comment]
Oh cool! I'm glad that it was helpful. I *definitely* need to blog about this; so many people have this problem :-)

Thanks a lot for reporting back!
