### ISSUE TITLE
Dockerfile VOLUME not working

### ISSUE THREAD

**Issue by zedtux** [jpetazzo/dind#36]
Given this image is ran as the following:

```
docker run --privileged --name docker -d -p 2375 -e PORT=2375 jpetazzo/dind
```

And another image is ran:
- linked to the dind image
- with Docker is installed
- with DOCKER_HOST set to the dind image IP and port
- with a volume from a folder including a Dockerfile
- the Dockerfile has the `VOLUME` instruction like the following: `VOLUME .:/app/`

When I run `docker build -t zedtux/test .`
And I open a bash session within the `zedtux/test` image and list the files from `/app/`
Then I see an empty folder

---

FYI using the `ADD` instruction instead of the `VOLUME` is working perfectly.

---

Do you know if volumes are supported in the dind image ?
Could it be that [this Docker issue](https://github.com/docker/docker/issues/4023) is the reason of my issue ?

**Comment by jpetazzo** [comment]
Closing old issues.
