### ISSUE TITLE
Fine-grained security

### ISSUE THREAD

**Issue by selipso** [jpetazzo/dind#43]
Now that Docker supports --cap-add and --cap-drop, it would be good to know which security settings to use with dind in case you wanted to make a public-facing docker instance.

Dealing with CAP_NET_SYSADMIN is going to be tricky.

**Comment by jpetazzo** [comment]
That's a good idea, but there is still a long way to go — specifically because of `CAP_NET_SYSADMIN`.

If someone wants to experiment and confirm which set of caps will allow dind to run properly, I'll be happy to update the documentation!
