### ISSUE TITLE
Failure to remove btrfs snapshot

### ISSUE THREAD

**Issue by marclennox** [jpetazzo/dind#44]
I'm using DIND to do isolated docker image builds, and I'm always seeing the following issue when the container exits.

```
Error response from daemon: Cannot destroy container 272993725fb65d437a8bb52e66b4b54df9061d8f523d415186ed63073d2f3fb2: Driver btrfs failed to remove root filesystem 272993725fb65d437a8bb52e66b4b54df9061d8f523d415186ed63073d2f3fb2: Failed to destroy btrfs snapshot: directory not empty
```

The result is a container that I can't seem to destroy.  Any ideas how I can avoid this?

**Comment by jpetazzo** [comment]
Sweet! I'm closing this issue then.
