### ISSUE TITLE
sometimes it works, sometimes not

### ISSUE THREAD

**Issue by timglabisch** [jpetazzo/dind#45]
hi, i am trying to build a kubernetes cluster inside of docker using fig. i tryed to use the wrapdocker script.
sometimes after starting docker the minion or the master can run docker, sometimes not.

any ideas?

https://github.com/timglabisch/docker-fig-kubernetes

**Comment by jpetazzo** [comment]
Hi,

Do you still experience that issue?

If yes, I would recommend to:

- provide additional debugging info
- reach out to the k8s community as well

Thank you!

**Comment by timglabisch** [comment]
i gave up on this because docker in docker seems to not really suitable using kubernetes.
