### ISSUE TITLE
Issue running dind with Jenkins Docker plugin

### ISSUE THREAD

**Issue by christianTragesser** [jpetazzo/dind#64]
First I'd like to give thanks as this repo gave me a big head start in getting Docker inside Docker to work.  I have successfully used this Docker file as a basis to build my own image which runs a container inside itself, as long as I'm initiating the container manually with:

```
docker run -d --privileged <personal_dind_image>
``` 
I'm attempting to use the Jenkins Docker plugin to spawn on-demand slaves for integration tests against my Chef cookbooks using test-kitchen and docker as the test-kitchen driver.  Again, if I manually start the container, ssh into it as the jenkins user, clone the appropriate git repo into the container and run my tests it performs flawlessly everytime. However, in an attempt to automate this process with Jenkins and the Docker plugin - the test fail telling me, "level="fatal" msg="Post http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=: dial unix /var/run/docker.sock: no such file or directory".  I'm certain the "Run container privilaged" option is checked in the Jenkins plugin, the slave container is created with Privilage=true, and have been reduced to guessing this is an issue of the docker daemon inside my dind container not having enough time to start up before test-kitchen starts but I'm not certain that is the case.  I've tried hacking at the Jenkins configuration telling it 'sleep' for a given amount of seconds but no luck:

```
Building remotely on 626873aa30bf@dockerhost (jenkins_slave_label) in workspace /var/lib/jenkins/workspace/project-cookbook
Cloning the remote Git repository
Cloning repository git@project-repo.git
 > git init /var/lib/jenkins/workspace/project-cookbook # timeout=10
Fetching upstream changes from git@project-repo.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress 
git@project-repo.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url git@project-repo.git# timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@project-repo.git # timeout=10
Fetching upstream changes from git@project-repo.git
 > git -c core.askpass=true fetch --tags --progress 
git@project-repo.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision e8516ca3ddf1886469332642d37a31fcb8dd2f0c (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e8516ca3ddf1886469332642d37a31fcb8dd2f0c
 > git rev-list e8516ca3ddf1886469332642d37a31fcb8dd2f0c # timeout=10
[project-cookbook] $ /bin/sh -xe /tmp/hudson5357411377460816584.sh
+ sleep 5
+ kitchen test
-----> Starting Kitchen (v1.3.1)
-----> Cleaning up any prior instances of <server-centos>
-----> Destroying <server-centos>...
       Finished destroying <server-centos> (0m0.00s).
-----> Testing <server-centos>
-----> Creating <server-centos>...
       Sending build context to Docker daemon 
       time="2015-04-02T02:14:37Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=: dial unix /var/run/docker.sock: no such file or directory" 
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of docker -H unix:///var/run/docker.sock build - ----
STDOUT: Sending build context to Docker daemon
STDERR: time="2015-04-02T02:14:37Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=: dial unix /var/run/docker.sock: no such file or directory"
---- End output of docker -H unix:///var/run/docker.sock build - ----
Ran docker -H unix:///var/run/docker.sock build - returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
I do see the same error regardless of which docker command I provide in the Jenkins build configuration.  I've been grinding on this issue for a solid day now and cannot determine why the Docker daemon is not available when automating this process with Jenkins.  Any thoughts?

Docker host is ubuntu 14.04.1, dind image is ubuntu 14.04.1 based, and I'm using Docker client/server 1.5.0.

**Comment by jpetazzo** [comment]
Whoa, that's a complicated issue, and I feel tempted to completely work around it :-)

Have you considered bind-mounting the Docker socket inside your container?

I.e. `docker run -v /var/run/docker.sock:/var/run/docker.sock ...` ?

That will give access to your "upper" Docker daemon to your container. That way, you don't need Docker-in-Docker. Would that help?

**Comment by christianTragesser** [comment]
Mounting /var/run/docker.sock inside my slave container works if I'm attempting docker actions as root.  I'm seeing /var/run/docker.sock mounted inside the container with an owner of 'root' and the POSIX group ID of the docker host(upper docker instance), which does not coincide with the group ID of the docker group inside the container.  So any user I create for my slave container(jenkins) gets 'permission denied' regardless of adding them to the appropriate docker group.

**Comment by esben** [comment]
I am using a dind-based approach together with Jenkins Docker Plugin.  To make it work, I use something like this in ENTRYPOINT script:

<pre>
appStart () {
    docker -d --bip=172.18.42.1/16 \
        -H tcp://0.0.0.0:2375 \
        -H unix:///var/run/docker.sock \
        &
    exec /usr/sbin/sshd -D
}

if [ "$*" = "/usr/sbin/sshd -D" -o -z "$*" ] ; then
    cmd="app:start"
else
    cmd="$1"
fi

case "$cmd" in
    app:start)
        appStart
        ;;
    app:help)
        appHelp
        ;;
    *)
        if [ -x $1 ]; then
            $*
        else
            prog=$(which $1)
            if [ -n "${prog}" ] ; then
                shift 1
                $prog $@
            else
                appHelp
            fi
        fi
        ;;
esac
</pre>

**Comment by christianTragesser** [comment]
The more I troubleshoot, the more I think this maybe a test-kitchen conflict.  I resorted to having my host Docker service bound to all IPs and inside the dind container, pointing the test-kitchen Docker driver  to the Docker host docker0 bridge.  I'm going to close this issue.
