### ISSUE TITLE
Caching repository

### ISSUE THREAD

**Issue by kojiromike** [jpetazzo/dind#65]
One of the downsides of dind is that the inner host pulls images even if the outer host already has those images. I'm totally softballing this question, but to get the conversation started, have you considered ways to cache the images fetched by one inner docker host so that they can be used without real bandwidth pulls by another inner host?

**Comment by jpetazzo** [comment]
A few things would come to mind:

- running a local registry, and using images from the local registry
- running a mirror registry
- running an HTTP proxy (with SSL cert injection since we use HTTPS)

**Comment by JeanMertz** [comment]
@jpetazzo a host volume pointing to `/var/lib/docker` is technically out of the question?

**Comment by jpetazzo** [comment]
@JeanMertz: if two daemons share the same `/var/lib/docker` directory, terrible things can happen.

(Seriously: there is no locking mechanism here; it was one of the deliberate design decisions of Docker. Going through one unique daemons that synchronizes access, vs. multiple programs that have to coordinate, makes the design much simpler. Sorry!)

**Comment by aalexand** [comment]
I was also looking into making some images available out of the box in the built dind-enabled container.

Can this work: pre-create a tarball with Docker graph directory containing images of interest and ADD the tarball into /var/lib/docker of the dind-enabled container being build?

OK, I actually tried it and one problem appears to be the whiteout files as if the graph directory being ADD'ed has any of those the daemon chokes on adding those.  I wonder if there is a way to overcome this.

**Comment by jpetazzo** [comment]
I would just use `docker load`, personally.

**Comment by thaJeztah** [comment]
If you consider caching as an option; this may be of interest to you https://github.com/docker/distribution/pull/779 (and https://github.com/docker/distribution/pull/610) and the description; https://github.com/docker/distribution/issues/459

**Comment by jpetazzo** [comment]
Closing old issues.
