### ISSUE TITLE
mkdir -p fails without reason in dind: concurrency problem

### ISSUE THREAD

**Issue by DanielMahu** [jpetazzo/dind#73]
Run inside dind, any docker build command that includes compiling packages from source with the -j option to paralellize compilation fails randomly with the error:

```
    mkdir: can't create directory 'some/name': No such file or directory
```

A small test case that fails quickly on the setup I used – 32 cores x86_64 Linux 3.13.0-45-generic Ubuntu 14.04.2, Docker 1.5.0 – is available here:

https://gist.github.com/DanielMahu/6e7104c2168910363176

**Comment by jpetazzo** [comment]
Just ran it (`sh run .sh`) on my machine (quad core, Docker 1.6.0 with AUFS) and all went fine.

Do you still have this problem?

**Comment by DanielMahu** [comment]
In the meantime I discovered that the issue only happens if the storage drivers are AUFS both in the host docker daemon and in the one running in the container. So, as a workaround, I've switched to a different driver on one of them.

On the other hand, with AUFS storage drivers, and enough parallelism, it still happens. Might be a bug in the filesystem implementation of mkdir.

A quad core might not be sufficient to reproduce the bug, I tried on the cloud with a smaller instance and it worked fine. I've recorded a screen cast reproducing the bug (also on the cloud) on a 32 core instance. To factor out network delays, I redirected stdout while recording the final command.

The 1-minute recording can be seen here: https://asciinema.org/a/27837

(Most of) the commands I've typed during the demo are here:
https://gist.github.com/DanielMahu/5a314c0b6057d0f23332

**Comment by jpetazzo** [comment]
OK.

So if you try to build the problematic Dockerfile in Docker(AUFS)-in-Docker(AUFS), you hit the bug.

If you switch to another storage driver, you don't hit the bug. Did you switch the inner or outer Docker? What happens if you try to switch the other one? What happens if you try to build straight on Docker(AUFS)?

Thank you!

**Comment by jpetazzo** [comment]
Closing old issues. If somebody else hits this issue, just switch one of the volume drivers to something else.

(For the record, Play-With-Docker is using `devicemapper` in the "outer" Docker and `overlay2` in the "inner" Docker and it works great!)
