### ISSUE TITLE
Help with port forward

### ISSUE THREAD

**Issue by jaitaiwan** [jpetazzo/dind#77]
Hi!

I have a boot2docker vm which contains a docker vm in which I'm running a privileged dind container. What I'm trying to figure out is how I would access say port 80 in the lowest part of the docker daemon...

So visually:
Host -> boot2docker (192.168.99.100) -> docker (:2376) -> dind (:4444 exposed as :32772) -> nginx (:80)

How would I expose nginx:80?

Thanks in advance!

**Comment by jpetazzo** [comment]
You would have to e.g.:

- start the dind container with `-p 20080:10080`
- start the NGINX container with `-p 10080:80`

Now you can connect to NGINX by connecting to the boot2docker VM on port 20080.

If you want to reach NGINX from outside, you could map port 30080 of your host to port 20080 on the b2d VM and voilà!

Note: you wrote "I have a b2d VM which contains a Docker VM", do you really have a VM in a VM? Or just Docker running in b2d? (I assumed it was a typo...)

**Comment by jaitaiwan** [comment]
Yeh I meant a b2d vm which contains the docker daemon. Ended up reverese
engineering the iptables to make it dynamic

**Comment by jpetazzo** [comment]
OK, cool! I'm closing this issue then. Thank you!
