### ISSUE TITLE
mounted host volume empty when daemon outside dind

### ISSUE THREAD

**Issue by Jason-Green-Aver** [jpetazzo/dind#78]
I develop 'app' on an OSX laptop ('host') that runs a docker-daemon inside VirtualBox ('dev') (created via docker-machine). As my ci/cd utility ('rouster') grows, so do its dependencies. To encapsulate them, I've created an image ('rind'), which inherits from dind.

Happily, I can mount ~/src from host to rind and mount it again from rind to app and it works.

Presently, I use both `eval $(docker-machine env dev) && rind deploy` and `$(docker-machine env prod) && rind deploy`.  

Uncertain that prod should run dind, I repointed rind's client at dev's daemon by setting env_vars ( DOCKER_CERT_PATH, DOCKER_TLS_VERIFY, DOCKER_HOST, and DOCKER_MACHINE_NAME).

Sadly, app now sees the mounted volumes, but they have no contents.

Thank you for these terrific tools and for any advice you may have.

**Comment by jpetazzo** [comment]
I suppose that your CI/CD utility (rouster) uses Docker, right? That's why you're using dind in the first place?

**Comment by Jason-Green-Aver** [comment]
Correct. Rouster uses both Docker and Docker-Compose.

**Comment by jpetazzo** [comment]
I wrote a blog post about that kind of use-case:

http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

I hope it helps!
