### ISSUE TITLE
Streaming logs of inner containers out to the outer one

### ISSUE THREAD

**Issue by lguminski** [jpetazzo/dind#80]
I think that working with Docker in Docker would be much easier if `docker logs` would stream logs of inner containers with a different colors each. 

This could look like this (the gif comes from our [blog post](http://container-solutions.com/?p=3031]))
![mydind](https://cloud.githubusercontent.com/assets/3329545/9006933/ceb694a4-378c-11e5-8b06-41ab18845dd4.gif)

A PR follows.

**Comment by jpetazzo** [comment]
Closing older issues. (But for the record, that PR was super cool.)
