### ISSUE TITLE
btrfs required?

### ISSUE THREAD

**Issue by larsks** [jpetazzo/dind#86]
The docs say:

> There is only one requirement: your Docker version should support the --privileged flag.

But trying to run the `dind` image I get:

    ERRO[0000] [graphdriver] prior storage driver "btrfs" failed: prerequisites for driver not satisfied (wrong filesystem?) 
    FATA[0000] Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?) 

So I guess there is a second requirement?

**Comment by frankscholten** [comment]
We, me and @lguminski, encountered the same issue

```
frank@franktop:~/src/mesos-local$ docker run -it --privileged jpetazzo/dind bash
Unable to find image 'jpetazzo/dind:latest' locally
latest: Pulling from jpetazzo/dind
b3fdd07260ba: Pull complete 
bb6688786635: Pull complete 
a8bd4775a00b: Pull complete 
f99df281df13: Pull complete 
b9b28823f7bf: Pull complete 
f224fde2d7ec: Pull complete 
551c213472f6: Pull complete 
d3a1f33e8a5a: Already exists 
c22013c84729: Already exists 
d74508fb6632: Already exists 
91e54dfb1179: Already exists 
Digest: sha256:c649b6dacda1c21a3d5b45148f2586bce139b5696026d72edcbdc04b63ba5b75
Status: Downloaded newer image for jpetazzo/dind:latest
root@207f57565f45:/# ls -al /var/lib/docker/
btrfs/ tmp/   
root@207f57565f45:/# ls -al /var/lib/docker/^C
root@207f57565f45:/# wrapdocker 
ERRO[0000] [graphdriver] prior storage driver "btrfs" failed: prerequisites for driver not satisfied (wrong filesystem?) 
FATA[0000] Error starting daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?) 
^C
```

This is probably because the base image was updated?

**Comment by jpetazzo** [comment]
Can you add the output of:

```
docker version
docker info
mount
```

Thanks!

**Comment by tompson** [comment]
running into the same issue, here is the required information:

    % docker version
    Client:
    Version:      1.8.1
    API version:  1.20
    Go version:   go1.4.2
    Git commit:   d12ea79
    Built:        Thu Aug 13 02:35:49 UTC 2015
    OS/Arch:      linux/amd64

    Server:
    Version:      1.8.1
    API version:  1.20
    Go version:   go1.4.2
    Git commit:   d12ea79
    Built:        Thu Aug 13 02:35:49 UTC 2015
    OS/Arch:      linux/amd64

    % docker info
    Containers: 34
    Images: 410
    Storage Driver: aufs
    Root Dir: /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 549
    Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-62-generic
    Operating System: Ubuntu 14.04.2 LTS
    CPUs: 8
    Total Memory: 31.29 GiB
    Name: nepal
    ID: L6PS:MWAZ:W4QH:PNMA:WOYU:HTXE:2FX2:JNUE:NPWL:6F77:26SG:2LZ2
    Username: tompson
    Registry: https://index.docker.io/v1/
    WARNING: No swap limit support

    % mount
    /dev/md2 on / type ext4 (rw)
    proc on /proc type proc (rw)
    sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
    none on /sys/fs/cgroup type tmpfs (rw)
    none on /sys/fs/fuse/connections type fusectl (rw)
    none on /sys/kernel/debug type debugfs (rw)
    none on /sys/kernel/security type securityfs (rw)
    udev on /dev type devtmpfs (rw,mode=0755)
    devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
    tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
    none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
    none on /run/shm type tmpfs (rw,nosuid,nodev)
    none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
    none on /sys/fs/pstore type pstore (rw)
    cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
    /dev/md1 on /boot type ext3 (rw)
    s3fs on /mnt/backup type fuse.s3fs (rw,allow_other)
    systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)

**Comment by jpetazzo** [comment]
There is now an official [docker:dind](https://hub.docker.com/_/docker/) image upstream! I invite you to test it, since it is actively maintained. Thank you!
