### ISSUE TITLE
Unable to mount volumes on containers inside the dind container

### ISSUE THREAD

**Issue by RayRutjes** [jpetazzo/dind#90]
Actually if I spawn a new container with a volume from inside this image, then the volume is not mounted.
If I try to mount a unique file to the spawned container, the file is turned into an empty directory on the container.

Is it possible to use volumes on containers spawned inside of this dind image?

**Comment by jpetazzo** [comment]
I'm sorry, I don't understand what you're trying to do, it is a bit confusing :-(

It is totally possible to use volumes all the way down, i.e.:
- share a directory between your Docker host (e.g. `/mnt`) and your DinD container (on e.g. `/data`)
- then share a directory from the DinD container (e.g. `/data/containerX`) to a container started in DinD (e.g. `/var/lib`)

You just have to specify the right `-v` options each time.
