### ISSUE TITLE
Can't use --priviliged flag: any workaround?

### ISSUE THREAD

**Issue by masavini** [jpetazzo/dind#92]
Hi,
I'm trying to set up a "docker factory" on Bluemix Containers. My upload bandwith is pretty low and it takes ages to upload my images from the laptop...

Bleumix, however, does not allow privileged containers:
```
# docker run hello-world
Post http:///var/run/docker.sock/v1.19/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
```

Is there any workaround you may suggest?
Thanks

**Comment by jpetazzo** [comment]
Unfortunately, if you can't run privileged containers, you won't be able to run Docker-in-Docker.

You might be able to work around the issue if you have access to capabilities, though.
