### ISSUE TITLE
/usr/local/bin/wrapdocker: line 100: docker: command not found

### ISSUE THREAD

**Issue by rheinwein** [jpetazzo/dind#96]
Pulling down the latest dind image and running the commands in the README results in this error. 

```
$ docker run --privileged -t -i dind
/usr/local/bin/wrapdocker: line 100: docker: command not found

exit
```

It looks like the failures started after the build with id b9bmvvmja6wpyacvgmhzkit (20 Nov 2015).

**Comment by jpetazzo** [comment]
I had never seen this, I'm so sorry :see_no_evil:

**Comment by rheinwein** [comment]
Haha, I forgot about it, and somehow came across a GitHub view that listed all of my open issues. I figure that sometime in the last 3 years, we fixed this 😆
