### ISSUE TITLE
CentOS 7 dind image

### ISSUE THREAD

**Issue by judoole** [jpetazzo/dind#98]
Is that doable? Using this via copy-paste

```docker
FROM centos:7

# Install docker
RUN yum -y -q install docker

# Install the magic wrapper.
ADD ./wrapdocker /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker

# Define additional metadata for our image.
VOLUME /var/lib/docker
CMD ["wrapdocker"]
```
and running ```docker run --privileged=true dind_centos``` results in
```level=error msg="Couldn't run auplink before unmount: exec: \"auplink\": executable file not found in $PATH"```

**Comment by jpetazzo** [comment]
I recommend to use the official `docker:dind` image instead. :)

**Comment by judoole** [comment]
Yes, found out after reading all of the README.md :)
Should have closed this one myself afterwards. Thx anyways!
