### ISSUE TITLE
Nodejs Dind image

### ISSUE THREAD

**Issue by ambodi** [jpetazzo/dind#99]
I was wondering how can someone extend your image with node? I tried this: https://gist.github.com/thom-nic/724a2af410e90a654e35 but it gives an error

`sudo apt-get not found`

**Comment by jpetazzo** [comment]
I don't recommend that; I'm 99% sure that there is an easier way :-)

Can you describe what you are trying to do?

**Comment by jpetazzo** [comment]
Closing old issues.
